### ISSUE TITLE
Issue running it in macOS

### ISSUE THREAD

**Issue by idarek** [harttle/disqus2github#1]
Hello.
I know, that repo is 3 years old, but wonder if is still valid? Tried to run it on macOS with the following errors.

<img width="1038" alt="node_errors_1" src="https://user-images.githubusercontent.com/271114/108588528-9f793c80-7351-11eb-9100-c635e8e16833.png">
<img width="1038" alt="node_errors_2" src="https://user-images.githubusercontent.com/271114/108588527-9daf7900-7351-11eb-9afc-dc3b46cfaabe.png">
<img width="1038" alt="node_errors_3" src="https://user-images.githubusercontent.com/271114/108588522-9a1bf200-7351-11eb-806f-b4cc4efb02f3.png">

**Comment by harttle** [comment]
It's related to [xml2json](https://www.npmjs.com/package/xml2json). Try upgrade it or replace with another xml parser. This repo is meant to be a scaffold instead of a versatile cli tool. Try tweak it around and if you find it useful for everyone, I'm happy to have your PR.

**Comment by idarek** [comment]
No worry, not my work field hence will try to find other tool. Thanks.
